name: Playwright Tests

on: 
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    env:
      USER_PASS: ${{ secrets.USER_PASS }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      TESTMAIL_JSON: ${{ secrets.TESTMAIL_JSON }}
      TESTMAIL_ADRESS: ${{ secrets.TESTMAIL_ADRESS }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      
      - name: Set up environment
        run: |
          sed -i 's/{TMS_TOKEN}/${{ secrets.TMS_TOKEN }}/g' connection_config.ini

      - name: Run tests
        run: pytest

      # Загрузка артефактов
      - name: Uploading artefacts
        uses: actions/upload-artifact@v4
        with:
          name: allure_report
          path: allure-report/

      # Получение истории прогонов Allure из артефактов
      - name: Download Allure history
        uses: actions/download-artifact@v3
        with:
          name: allure-history
          path: allure-results/history

      # Генерация отчета с историей
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-results/history

      # Публикация отчета Allure с историей
      - name: Publish Allure report with history
        uses: peaceiris/actions-gh-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
